version: "3.5"

services:
  postgres:
    container_name: asc_postgres
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./db:/docker-entrypoint-initdb.d