version: "3.5"

services:
  # API 1
  api1:
    build: .
    container_name: api1
    hostname: api1
    env_file:
      - path: ./.env
    depends_on:
      - postgres
      - redis
    expose:
      - "80:80"
    deploy:
      resources:
        limits:
          cpus: "0.15"
          memory: "0.4GB"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/health"]
      interval: 10s
      timeout: 5s
      retries: 5

  # API 2
  api2:
    build: .
    container_name: api2
    hostname: api2
    env_file:
      - path: ./.env
    depends_on:
      - postgres
      - redis
    expose:
      - "80:80"
    deploy:
      resources:
        limits:
          cpus: "0.15"
          memory: "0.4GB"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/health"]
      interval: 10s
      timeout: 5s
      retries: 5

  # NGINX
  nginx:
    image: nginx
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api1
      - api2
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: "0.15"
          memory: "0.5GB"

  # DATABASE
  postgres:
    image: postgres:15
    container_name: postgres
    hostname: postgres
    command: postgres -c log_min_messages=FATAL
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    deploy:
      resources:
        limits:
          cpus: "0.7"
          memory: "1.3GB"
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DATABASE_USER} -d ${DATABASE_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 10s

  # REDIS
  redis:
    image: redis
    hostname: redis
    container_name: redis
    command: redis-server --save "" --appendonly no --maxclients 20000
    ports:
      - "127.0.0.1:6379:6379"
    deploy:
      resources:
        limits:
          cpus: '0.15'
          memory: '0.3GB'
