version: "3.5"

services:
  # API 1
  api1:
    build: .
    hostname: api1
    env_file:
      - .env
    environment:
      PORT: "80"
      DATABASE_URL: postgres://postgres:postgres@db/postgres
      POOL_SIZE: 30
      REDIS_HOST: localhost
      DB_HOST: localhost
    depends_on:
      - db
      - redis
    expose:
      - "80"
    deploy:
      resources:
        limits:
          cpus: "0.15"
          memory: "0.4GB"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/health"]
      interval: 10s
      timeout: 5s
      retries: 5

  # API 2
  api2:
    build: .
    hostname: api2
    env_file:
      - .env
    environment:
      PORT: "80"
      DATABASE_URL: postgres://postgres:postgres@db/postgres
      POOL_SIZE: 30
      REDIS_HOST: localhost
      DB_HOST: localhost
    depends_on:
      - db
      - redis
    expose:
      - "80"
    deploy:
      resources:
        limits:
          cpus: "0.15"
          memory: "0.4GB"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/health"]
      interval: 10s
      timeout: 5s
      retries: 5

  # NGINX
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api1
      - api2
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: "0.15"
          memory: "0.5GB"

  # DATABASE
  db:
    image: postgres:15
    container_name: postgres
    volumes:
      - ./db/sql_entry.sql:/docker-entrypoint-initdb.d/init.sql
    command: postgres -c log_min_messages=FATAL
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: postgresdb
    ports:
      - "5432:5432"
    deploy:
      resources:
        limits:
          cpus: "0.7"
          memory: "1.3GB"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 10s
    
  # REDIS
  redis:
    image: redis
    hostname: redis
    network_mode: host
    command: redis-server --save "" --appendonly no --maxclients 20000
    deploy:
      resources:
        limits:
          cpus: '0.15'
          memory: '0.3GB'